name: "Rapido Changeset"

on:
  workflow_dispatch:
    inputs:
      packageData:
        description: "Table data, to produce contents of package.xml"
        required: true
      destructivePreData:
        description: "Table data, to produce contents of package.xml for pre-destrictive changes"
        required: true
      destructivePostData:
        description: "Table data, to produce contents of package.xml for post-destrictive changes"
        required: true
      branch:
        description: "Branch on which to work"
        default: "main"
      commit_message:
        description: "Commit message added when committing the package.xml"
        default: "Created by Rapido Companion"
      sfdx-docker-image:
        description: "Salesforce DX CLI version, for using the CLI docker image (ex: salesforce/salesforcedx:7.190.2-slim)"
        default: "salesforce/salesforcedx:7.207.5-slim"
      path_package_xml:
        description: "Path to the package.xml file"
        required: true
      path_package_xml_destructive_pre:
        description: "Path to the package.xml file for destructive changes pre deploy"
      path_package_xml_destructive_post:
        description: "Path to the package.xml file for destructive changes post deploy"
      salesforce_sfdx_auth_url:
        description: "Salesforce DX auth url"

jobs:
  #########################################################################
  # Retrieve package from Salesforce (source org)
  # commit to Github,
  # deploy to Salesforce (target org)
  #

  rapido_changeset:
    runs-on: ubuntu-latest
    container: ${{ inputs.sfdx-docker-image }}
    name: "Changeset : generate package.xml manifests, retrieve, commit, deploy"
    env:
      folder-to-commit: .
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Generate package.xml
        uses: RupertBarrow/actions/action-create-sfdx-package-xml@feature/53-debug-issue-with-action-create-sfdx-package-xml
        with:
          contents: ${{ github.event.inputs.packageData }}
          path: "${{ github.event.inputs.path_package_xml }}"

      - name: Generate package.xml for destructive-changes-pre
        if: "${{ github.event.inputs.destructivePreData }}"
        uses: RupertBarrow/actions/action-create-sfdx-package-xml@feature/53-debug-issue-with-action-create-sfdx-package-xml
        with:
          contents: ${{ github.event.inputs.destructivePreData }}
          path: "${{ github.event.inputs.path_package_xml_destructive_pre }}"

      - name: Generate package.xml for destructive-changes-post
        if: "${{ github.event.inputs.destructivePostData }}"
        uses: RupertBarrow/actions/action-create-sfdx-package-xml@feature/53-debug-issue-with-action-create-sfdx-package-xml
        with:
          contents: ${{ github.event.inputs.destructivePostData }}
          path: "${{ github.event.inputs.path_package_xml_destructive_post }}"

      - name: Retrieve metadata from Salesforce (source org)
        uses: RupertBarrow/actions/action-command@v3
        with:
          salesforce_sfdx_auth_url: ${{ github.event.inputs.salesforce_sfdx_auth_url }}
          command: "sfdx force:source:retrieve -x ${{ github.event.inputs.path_package_xml }}"

      - name: Commit to Github
        uses: RupertBarrow/actions/action-commit@v3
        with:
          commit_message: ${{ github.event.inputs.commit_message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Command options for deploy
        id: deployOptions
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            let options = "-x '${{ github.event.inputs.path_package_xml }}'"
            if ( "this${{ github.event.inputs.path_package_xml_pre }}" !== "this" ) {
              options += " --predestructivechanges='${{ github.event.inputs.path_package_xml_destructive_pre }}'"
            }
            if ( "this${{ github.event.inputs.path_package_xml_post }}" !== "this" ) {
              options += " --postdestructivechanges='${{ github.event.inputs.path_package_xml_destructive_post }}'"
            }
            return options

      - name: Deploy metadata to Salesforce (target org)
        uses: RupertBarrow/actions/action-command@v3
        with:
          salesforce_sfdx_auth_url: ${{ github.event.inputs.salesforce_sfdx_auth_url }}
          command: "sfdx force:source:deploy ${{ steps.deployOptions.outputs.result }}"
