name: "Rapido Changeset List"

on:
  workflow_dispatch:
    inputs:
      salesforce_sfdx_auth_url:
        description: "Salesforce DX auth url for the sandbox org"
        required: true
      #salesforce_instance_url:
      #  description: "Salesforce instance url where to look for changesets"
      #  required: true
      #salesforce_username:
      #  description: "Salesforce username, necessary to login with the sf cli plugin"
      #  required: true
      #  default: "barrow.rapido@flowbird.group.devrupert"
      branch:
        description: "Branch on which to work"
        default: "main"
      filename:
        description: "Filename used to store the changesets list"
        default: "manifest/changesets-outbound.json"
      commit_message:
        description: "Commit message added when committing the changesets list file"
        default: "Created by Rapido Companion"
      sfdx-docker-image:
        description: "Salesforce DX CLI version, for using the CLI docker image (ex: salesforce/salesforcedx:7.190.2-slim)"
        #default: "salesforce/cli:2.17.5-slim"
        default: "rupertbarrow/rapido-sf-cli:latest"

jobs:
  #########################################################################
  # Get list of changesets from Salesforce
  #

  rapido_changeset_list:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.sfdx-docker-image }}
      #options: --user root
    name: "List changesets"
    env:
      folder-to-commit: .
    permissions:
      contents: write
    outputs:
      changesets: ${{ steps.changeset_list.outputs.changesets }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Get changeset list
        id: changeset_list
        shell: bash
        run: |
          # Node and the sf cli are already installed in the Docker image container
          echo y | sf plugins:install rapido-sf-plugin

          # Login to the org
          sf org login sfdx-url --set-default --alias checkout --sfdx-url-file <(echo ${{ github.event.inputs.salesforce_sfdx_auth_url }})

          # List changesets to output
          echo changesets=$(sf rapido:scrape:changeset:list -o checkout --json) >> "$GITHUB_OUTPUT"

          # List changesets to file
          set -x
          pwd
          ls -al
          mkdir -p `dirname ${{ github.event.inputs.filename }}`
          echo ${{ steps.changeset_list.outputs.changesets }} > ${{ github.event.inputs.filename }}

          # Add and commit the changesets list file
          git config --global --add safe.directory `pwd`
          git config --local user.name  ${{github.actor}}
          git config --local user.email ${{github.actor}}@users.noreply.github.com
          git config --add safe.directory .
          git add "${{ github.event.inputs.filename }}"
          git commit --allow-empty -m "${{ github.event.inputs.commit_message }}"

      - name: Output changesets list to an annotation
        uses: dkhunt27/action-annotations@v1
        with:
          type: notice
          msg: ${{ steps.changeset_list.outputs.changesets }}
