name: "Rapido Deploy"
# Deploy a package.xml from a source org to a target org

on:
  workflow_dispatch:
    inputs:
      packageData:
        description: "Table data, to produce contents of package.xml, including pre- and post-destructive changes"
        required: true
      branch:
        description: "Branch on which to work"
        default: "main"
      commit_message:
        description: "Commit message added when committing the package.xml"
        default: "Created by Rapido Companion"
      sfdx-docker-image:
        description: "Salesforce DX CLI version, for using the CLI docker image (ex: salesforce/salesforcedx:7.190.2-slim)"
        default: "salesforce/salesforcedx:7.207.5-slim"
      path_package_xml:
        description: "Path to the package.xml file"
        required: true
      path_package_xml_destructive_pre:
        description: "Path to the package.xml file for destructive changes pre deploy"
      path_package_xml_destructive_post:
        description: "Path to the package.xml file for destructive changes post deploy"
      salesforce_sfdx_auth_url_source:
        description: "Salesforce DX auth url for source org"
        required: true
      salesforce_sfdx_auth_url_target:
        description: "Salesforce DX auth url for target org"
        required: true

jobs:
  #########################################################################
  # Retrieve package from Salesforce (source org)
  # commit to Github,
  # deploy to Salesforce (target org)
  #

  rapido_changeset:
    runs-on: ubuntu-latest
    container: ${{ inputs.sfdx-docker-image }}
    name: "Changeset : generate package.xml manifests, retrieve, commit, deploy"
    env:
      folder-to-commit: .
      input_data: ${{ fromJSON(github.event.inputs.data) }}
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: DEBUG
        run: |
          echo "DEBUG: data: $input_data"
          echo "DEBUG: data.packageData: ${{ fromJSON(github.event.inputs.data).packageData }}"
          echo "DEBUG: data.destructivePreData: ${{ fromJSON(github.event.inputs.data).destructivePreData }}"
          echo "DEBUG: data.destructivePostData: ${{ fromJSON(github.event.inputs.data).destructivePostData }}"

      - name: DEBUG2
        if: ${{ fromJSON(github.event.inputs.data).packageData }}
        run: |
          echo "DEBUG2: data.packageData: ${{ fromJSON(github.event.inputs.data).packageData }}"

      - name: Generate package.xml
        if: ${{ fromJSON(github.event.inputs.data).packageData }}
        uses: RupertBarrow/actions/action-create-sfdx-package-xml@v3
        with:
          contents: ${{ fromJSON(github.event.inputs.data).packageData }}
          path: "${{ github.event.inputs.path_package_xml }}"

      - name: Generate package.xml for destructive-changes-pre
        if: ${{ fromJSON(github.event.inputs.data).destructivePreData }}
        uses: RupertBarrow/actions/action-create-sfdx-package-xml@v3
        with:
          contents: ${{ fromJSON(github.event.inputs.data).destructivePreData }}
          path: "${{ github.event.inputs.path_package_xml_destructive_pre }}"

      - name: Generate package.xml for destructive-changes-post
        if: ${{ fromJSON(github.event.inputs.data).destructivePostData }}
        uses: RupertBarrow/actions/action-create-sfdx-package-xml@v3
        with:
          contents: ${{ fromJSON(github.event.inputs.data).destructivePostData }}
          path: "${{ github.event.inputs.path_package_xml_destructive_post }}"

      - name: Retrieve metadata from Salesforce (source org)
        uses: RupertBarrow/actions/action-command@v3
        with:
          salesforce_sfdx_auth_url: ${{ github.event.inputs.salesforce_sfdx_auth_url_source }}
          command: "sfdx force:source:retrieve -x ${{ github.event.inputs.path_package_xml }}"

      - name: Commit to Github
        uses: RupertBarrow/actions/action-commit@v3
        with:
          commit_message: ${{ github.event.inputs.commit_message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Command options for deploy
        id: deployOptions
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            let options = "-x '${{ github.event.inputs.path_package_xml }}'"
            if ( "this${{ github.event.inputs.path_package_xml_pre }}" !== "this" ) {
              options += " --predestructivechanges='${{ github.event.inputs.path_package_xml_destructive_pre }}'"
            }
            if ( "this${{ github.event.inputs.path_package_xml_post }}" !== "this" ) {
              options += " --postdestructivechanges='${{ github.event.inputs.path_package_xml_destructive_post }}'"
            }
            return options

      - name: Deploy metadata to Salesforce (target org)
        uses: RupertBarrow/actions/action-command@v3
        with:
          salesforce_sfdx_auth_url: ${{ github.event.inputs.salesforce_sfdx_auth_url_target }}
          command: "sfdx force:source:deploy ${{ steps.deployOptions.outputs.result }}"
