name: "Rapido Changeset List"

on:
  workflow_dispatch:
    inputs:
      salesforce_sfdx_auth_url:
        description: "Salesforce DX auth url for the sandbox org"
        required: true
      salesforce_instance_url:
        description: "Salesforce instance url where to look for changesets"
        required: true
      branch:
        description: "Branch on which to work"
        default: "main"
      commit_message:
        description: "Commit message added when committing the package.xml"
        default: "Created by Rapido Companion"
      sfdx-docker-image:
        description: "Salesforce DX CLI version, for using the CLI docker image (ex: salesforce/salesforcedx:7.190.2-slim)"
        #default: "salesforce/salesforcedx:7.207.5-slim"
        #default: "salesforce/cli:2.15.9-slim"
        # We don't use a Salesforce Docker image, because we need to controle the Node version - see https://github.com/forcedotcom/cli/issues/2550#issuecomment-1788958526
        default: "heroku/heroku:22"
      #outputs:
    #  changeset_list:
    #    description: "JSON list of changesets, with id, name, isIncoming, isOutgoing"
    #    value: ${{ jobs.changeset_list.outputs.changeset_list }}

jobs:
  #########################################################################
  # Get list of changesets from Salesforce
  #

  rapido_changeset_list:
    runs-on: ubuntu-latest
    container: ${{ inputs.sfdx-docker-image }}
    name: "List changesets"
    env:
      folder-to-commit: .
    permissions:
      contents: write
    #outputs:
    #  changeset_list: ${{ steps.changeset_list.outputs.lst }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18.17

      - name: Install Puppeteer dependencies
        run: |
          sudo apt install libnss3
          sudo apt-get install libatk1.0-0 
          sudo apt-get install libatk-bridge2.0-0 
          sudo apt-get install libx11-xcb1 
          sudo apt-get install libxcb-dri3-0 
          sudo apt-get install libxcomposite1 
          sudo apt-get install libxdamage1 
          sudo apt-get install libxfixes3 
          sudo apt-get install libcups2 
          sudo apt-get install libdrm2 
          sudo apt-get install libxrandr2 
          sudo apt-get install libgbm1 
          sudo apt-get install libasound2 
          sudo apt-get install libpangocairo-1.0-0 
          sudo apt-get install libgtk-3-0

      - name: Install the SF CLI and the Rapido SF CLI plugin
        run: |
          # This installs the CLI *without* its own version of node - see https://github.com/forcedotcom/cli/issues/2550#issuecomment-1788958526
          npm install @salesforce/cli --global
          echo y | sf plugins:install rapido-sf-plugin

      - name: Return the list of changesets
        uses: RupertBarrow/actions/action-command@feature/54-upgrade-action-command-to-work-with-sf-cli
        with:
          salesforce_sfdx_auth_url: ${{ github.event.inputs.salesforce_sfdx_auth_url }}
          #command: 'sf rapido:scrape:changeset:list --json -u $(sf org open --url-only --json | grep url | sed "s/\"url\"://" | sed "s/,//" | sed "s/\"//g" | sed "s/ //g") > OUTPUT.json'
          command: 'sf rapido:scrape:changeset:list --json -u $(sf org open --url-only --json | grep url | sed "s/\"url\"://" | sed "s/,//" | sed "s/\"//g" | sed "s/ //g")'

      - run: cat OUTPUT.json
        shell: bash
