name: "Rapido Changeset List3"

on:
  workflow_dispatch:
    inputs:
      salesforce_sfdx_auth_url:
        description: "Salesforce DX auth url for the sandbox org"
        required: true
      salesforce_instance_url:
        description: "Salesforce instance url where to look for changesets"
        required: true
      salesforce_username:
        description: "Salesforce username, necessary to login with the sf cli plugin"
        required: true
        default: "barrow.rapido@flowbird.group.devrupert"
      branch:
        description: "Branch on which to work"
        default: "main"
      commit_message:
        description: "Commit message added when committing the package.xml"
        default: "Created by Rapido Companion"
      sfdx-docker-image:
        description: "Salesforce DX CLI version, for using the CLI docker image (ex: salesforce/salesforcedx:7.190.2-slim)"
        #default: "salesforce/cli:2.17.5-slim"
        default: "rupertbarrow/rapido-sf-cli:latest"
jobs:
  #########################################################################
  # Get list of changesets from Salesforce
  #

  rapido_changeset_list:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.sfdx-docker-image }}
      #options: --user root
    name: "List changesets"
    env:
      folder-to-commit: .
    permissions:
      contents: write
    #outputs:
    #  changeset_list: ${{ steps.changeset_list.outputs.lst }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      #- uses: actions/setup-node@v3
      #  with:
      #    node-version: 18.18

      - name: Verify versions
        run: |
          set -x
          pwd
          npm install @salesforce/cli --global
          sf version
          echo y | sf plugins:install rapido-sf-plugin
          sf plugins
          sf rapido:scrape:changeset:list --help

          #which node
          #node --version
          #which npm
          #npm install puppeteer@21.5.0 puppeteer-core@21.5.0
          #ls -al /root/.cache/puppeteer/chrome/linux-119.0.6045.105/chrome-linux64
          #ls -al /root /root/.local /root/.local/share

          echo sf org login sfdx-url -f ./sfdxauthurl.txt --set-default --alias checkout
          echo ${{ github.event.inputs.salesforce_sfdx_auth_url }} > ./sfdxauthurl.txt
          sf org login sfdx-url -f ./sfdxauthurl.txt --set-default --alias checkout
          rm -f ./sfdxauthurl.txt

          sf org display --verbose
          sf org list
          echo $HOME
          ls -al ~ ~/.sf ~/.sfdx ~/.cache 

          sf rapido:scrape:changeset:list2 --json -o ${{ github.event.inputs.salesforce_username }}
