name: "Rapido Changeset List"

on:
  workflow_dispatch:
    inputs:
      salesforce_sfdx_auth_url:
        description: "Salesforce DX auth url for the sandbox org"
        required: true
      salesforce_instance_url:
        description: "Salesforce instance url where to look for changesets"
        required: true
      branch:
        description: "Branch on which to work"
        default: "main"
      commit_message:
        description: "Commit message added when committing the package.xml"
        default: "Created by Rapido Companion"
      sfdx-docker-image:
        description: "Salesforce DX CLI version, for using the CLI docker image (ex: salesforce/salesforcedx:7.190.2-slim)"
        #default: "salesforce/salesforcedx:7.207.5-slim"
        #default: "salesforce/cli:2.15.9-slim"
        # We don't use a Salesforce Docker image, because we need to controle the Node version - see https://github.com/forcedotcom/cli/issues/2550#issuecomment-1788958526
        #default: "heroku/heroku:22"
        #default: "ghcr.io/puppeteer/puppeteer:21.5.0"
        default: "rupertbarrow/rapido-sf-cli:latest"
      #outputs:
    #  changeset_list:
    #    description: "JSON list of changesets, with id, name, isIncoming, isOutgoing"
    #    value: ${{ jobs.changeset_list.outputs.changeset_list }}

jobs:
  #########################################################################
  # Get list of changesets from Salesforce
  #

  rapido_changeset_list:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.sfdx-docker-image }}
      #options: --user root
    name: "List changesets"
    env:
      folder-to-commit: .
      #HOME: /root
    permissions:
      contents: write
    #outputs:
    #  changeset_list: ${{ steps.changeset_list.outputs.lst }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Verify sf version
        run: |
          set -x
          pwd
          env
          echo $HOME
          sf version
          sf plugins
          sf rapido:scrape:changeset:list --help

      - name: Return the list of changesets
        uses: RupertBarrow/actions/action-command@feature/54-upgrade-action-command-to-work-with-sf-cli
        with:
          salesforce_sfdx_auth_url: ${{ github.event.inputs.salesforce_sfdx_auth_url }}
          #command: 'sf rapido:scrape:changeset:list --json -u $(sf org open --url-only --json | grep url | sed "s/\"url\"://" | sed "s/,//" | sed "s/\"//g" | sed "s/ //g") > OUTPUT.json'
          command: 'sf rapido:scrape:changeset:list --json -u $(sf org open --url-only --json | grep url | sed "s/\"url\"://" | sed "s/,//" | sed "s/\"//g" | sed "s/ //g")'
